-- Named trigger configurations managed by the user via MCP.
-- These are metadata records — the actual cron firing is handled by Vercel.
-- "name" is the human label (e.g. "morning_briefing").
create table if not exists triggers (
    id          uuid primary key default gen_random_uuid(),
    name        text not null unique,
    schedule    text not null,              -- cron expression, e.g. "0 9 * * *"
    action      text not null default 'morning_briefing',
    enabled     boolean not null default true,
    config      jsonb not null default '{}',
    last_run_at timestamptz,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- Pre-computed morning briefing snapshots generated by the 9am cron.
-- Poke reads the latest row instead of polling every extension individually.
create table if not exists daily_digests (
    id           uuid primary key default gen_random_uuid(),
    generated_at timestamptz not null default now(),
    sections     jsonb not null default '[]',   -- raw per-extension reminder arrays
    total_count  int not null default 0,
    raw_text     text not null default ''
);

-- seed the default morning briefing trigger
insert into triggers (name, schedule, action, config)
values (
    'morning_briefing',
    '0 9 * * *',
    'morning_briefing',
    '{"timezone": "America/Toronto"}'
)
on conflict (name) do nothing;
